---
- name: Start Configuration
  hosts: all
  serial: '{{  parallelRunCount }}'
  gather_facts: false
  
  tasks:
  
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
      become: true
      become_method: sudo